# 全局配置文件
global:
  # ......
# 告警插件配置
alerting:
  # ......
# 按照设定参数进行扫描加载，用于自定义报警规则，其报警媒介和route路由由alertmanager插件实现
rule_files:
  # ......

# 设定采集对象，这里既有静态设置也有设置服务发现
scrape_configs:
  # ......
  
  # 采集华为AC信息
  - job_name: "huawei_ac"
    scrape_interval: 15s
    scrape_timeout: 10s
    # file_sd_configs:  # 可启动文件自动发现机制
    #  - files:
    #    - /opt/monitor/prometheus/targets/huawei-ac.yml  # 定义AC的目标IP
    #    refresh_interval: 2m
    static_configs:
      - targets:
        - 192.168.1.2  # SNMP设备IP 如AC的管理IP
        # - tcp://192.168.1.3:1161  # SNMP设备使用自定义的TCP端口传输
    metrics_path: /snmp
    params:
      auth: [public_v2]   # generator.yml中自定义的认证模块名称
      module: [H3C_AC]    # generator.yml中自定义的指标模块名称
    relabel_configs:
    - source_labels: ["__address__"]
      target_label: __param_target
    - source_labels: ["__param_target"]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9116  # snmp_exporter服务器真实IP地址和端口 需要修改为snmp_exporter运行的监听地址和端口