# 全局配置文件
global:
  # ......
# 告警插件配置
alerting:
  # ......
# 按照设定参数进行扫描加载，用于自定义报警规则，其报警媒介和route路由由alertmanager插件实现
rule_files:
  # ......

# 设定采集对象，这里既有静态设置也有设置服务发现
scrape_configs:
  # ......
  
  # 采集华为AC信息
  - job_name: "ruijie_wireless"
    scrape_interval: 15s
    scrape_timeout: 10s
    file_sd_configs:
      - files:
        - /root/monitor/prometheus/targets/huawei-*.yml
        refresh_interval: 2m
    metrics_path: /snmp
    relabel_configs:
    - source_labels: ["__address__"]
      target_label: __param_target
    - source_labels: ["__param_target"]
      target_label: instance
    - target_label: __address__
      replacement: 172.17.40.54:9116 # snmp_exporter 服务IP地址
    - source_labels: ["module"] # 从自定义的目标标签获取指标模块名称
      target_label: __param_module
    - source_labels: ["auth"] # 从自定义的目标标签获取认证模块名称
      target_label: __param_auth